[net]
git-fetch-with-cli = true

[patch.crates-io]
embedded-hal = { git = "https://github.com/Dirbaio/embedded-hal", rev = "0e4a3fd08ab919a0b697368305cd3dd926319ed2"}
embedded-hal-bus = { git = "https://github.com/Dirbaio/embedded-hal", rev = "0e4a3fd08ab919a0b697368305cd3dd926319ed2"}
embedded-hal-async = { git = "https://github.com/Dirbaio/embedded-hal", rev = "0e4a3fd08ab919a0b697368305cd3dd926319ed2"}
embedded-hal-nb = { git = "https://github.com/Dirbaio/embedded-hal", rev = "0e4a3fd08ab919a0b697368305cd3dd926319ed2"}
embedded-hal-mock = { git = "https://github.com/Dirbaio/embedded-hal-mock", rev = "8558ae71d8ba311af57f9668a6cc4c33bdb1066c"}

#[patch.'https://github.com/embassy-rs/stm32-data-generated']
#stm32-metapac = { path = "/home/dirbaio/embassy/stm32-data/build/stm32-metapac" }
